export const mockUsers = [
  {
    id: 1,
    name: 'Alex',
    distance: 3,
    sport: 'Boxe anglaise',
    level: 'Intermédiaire',
    goal: 'Sparring',
    gear: 'Gants 14oz',
    avatar: '/avatars/alex.jpg',
  },
  {
    id: 2,
    name: 'Emma',
    distance: 7,
    sport: 'Muay Thaï',
    level: 'Débutant',
    goal: 'Cardio',
    gear: 'Gants 12oz, corde',
    avatar: '/avatars/emma.jpg',
  },

  {
    id: 3,
    name: 'Liam',
    distance: 10,
    sport: 'Judo',
    level: 'Avancé',
    goal: 'Compétition',
    gear: 'Gants 12oz, corde',
    avatar: '/avatars/liam.jpg',
  },

  {
    id: 4,
    name: 'Sophia',
    distance: 5,
    sport: 'Boxe Anglaise',
    level: 'Intermédiaire',
    goal: 'Amélioration technique',
    gear: 'Sac de frappe, gants 14oz',
    avatar: '/avatars/sophia.jpg',
  },
  {
    id: 5,
    name: 'John',
    distance: 9,
    sport: 'Muay Thaï',
    level: 'Débutant',
    goal: 'Cardio',
    gear: 'Gants 12oz, corde',
    avatar: '/avatars/john.jpg',
  },
];
